services:
  # Override for development - mount source code for hot reload
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    command: npm run dev
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules

  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    command: npm run dev
    volumes:
      - ./services/product-service:/app
      - /app/node_modules

  manager-service:
    build:
      context: ./services/manager-service
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    command: npm run dev
    volumes:
      - ./services/manager-service:/app
      - /app/node_modules
      - uploads_data:/app/uploads

  admin-service:
    build:
      context: ./services/admin-service
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    command: npm run dev
    volumes:
      - ./services/admin-service:/app
      - /app/node_modules

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    command: npm run dev
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
      - uploads_data:/app/uploads

  frontend:
    command: npm run dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next